# Generated by Django 4.2 on 2023-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abb', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('temperament', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('wikipedia_url', models.CharField(max_length=150)),
            ],
        ),
    ]
